### ISSUE TITLE
Aeldari - Drukhari: Separation of Unit Filter from Obsession Selection [overhaul]

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10135]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.21

**Platform:** Linux

**Dropbox:** No

**Description:** Lelith is not selectable in any of the Kabal detachments, she should be.
Per the codex she simply would not get the obsession.

**Comment by ThePants999** [comment]
I don't know if this should be a separate issue, but more broadly, it should be possible to select which Coven/Kabal/Wych Cult each unit is in when it's in a detachment of the "wrong" type. For example, if you took one patrol of Cult of Strife, one patrol of Red Grief and one Kabal patrol, and you had Wych Cult units in the Kabal patrol, it's important to have a record of whether said units are CoS or Red Grief, because although they get neither obsession, they're a valid target for either CoS strats or Red Grief strats depending on which they're designated as.

**Comment by FarseerVeraenthis** [comment]
This should be done, if there are issues, please raise a new report with sepcific steps to replicate the behaviour.
