### ISSUE TITLE
[v9.2.6] Grey Knights Stormraven Gunship pts incorrect

### ISSUE THREAD

**Issue by XcaliberRage** [BSData/wh40k-9e#10341]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** 
It seems in the last update the Stormraven Gunship for Grey Knights was modified to have a base points cost of 310 pts.

https://www.warhammer-community.com/wp-content/uploads/2021/05/DZsMnev8cLAMbnWI.pdf

As per the current pts costs for Grey Knights linked above (as far as I can identify this is what should be considered current), this should be 290pts. Additionally, no pts cost for a twin Assault cannon is listed, suggesting that it should be free, and not 10pts as it is listed in Battlescribe.

Apologies if my information is incorrect. I have yet to find anything that suggests the Grey Knights Stormraven is more expensive than a Space Marine Storm Raven though!

**Comment by tekton** [comment]
By Publication Order (which is our source of truth, even if pipelines are changed and being weird) the Codex came out after everything else. And in the codex it certainly is 310pts base (which is ridiculous, I know, I'm not debating that).

That said, that PDF with those points were also listed as what to use until the codex came out. 

https://www.warhammer-community.com/2021/05/27/5-of-the-biggest-points-drops-from-chapter-approved-2021/ 

"...to be used alongside their current codexes until their new books arrive."

Want to make it really murky now? Same article: "That’s because their codexes were intended to be out at this point, complete with their fancy new rules and updated points values."

So where does that leave us? Well, a slight comment in a random article is hard to use as "proof" for a 290pt Stormraven when said articles are also quite often wrong. I've sent messages for the FAQ to address things, but as it stands- GW's precedent of publication order wins
