### ISSUE TITLE
Aeldari - Drukhari: Kabalite Issue and something, something, relics, something

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10691]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Kabalits cant take 2 blasters for 5 models
Succubus lost ability to take relic from book of rust

**Comment by FarseerVeraenthis** [comment]
correct, Kabalite Warriors cannot take 2 blasters for 5 members, they can only take one, as stated in the codex and how BS is currently working.
I cannot help with the 'missing relic' since the name of the relic has not been provided, or any other details of when or how it is 'missing' - likely it is due to a wrong selection of warlord of obsession.
