### ISSUE TITLE
Imperium - Space Marines: Relics for Sergeants Stratagems not working correctly

### ISSUE THREAD

**Issue by MatteoCesari78** [BSData/wh40k-9e#10755]
Using the stratagem marked of command apparently opens the option to use a 4th relic, no matter what, even on a 4th character model, it should only let you pick a limited number of relics on a seargent model

**Comment by FarseerVeraenthis** [comment]
This is functioning in the sme way for all chapters, which means it is more broken than I can easily fix as it needs consideration at a Space Marine Library level rather than child catalogue level.
@acebaur this configuration is not correct - it should give an error, but does not;
![image](https://user-images.githubusercontent.com/23246922/147002800-1e377a7d-e0c5-4adc-b704-fecc636fa29c.png)

In this image, there should be an error stating that the Captain/Chaplain have 1 too many Relics between them, since they only get one 'free' with the Warlord selection. However, the effect of adding the Stratagem is allowing an extra relic to be given to any character, not just a Sgt.
I don't know how to resolve this issue, but it is likely o manifest across all Space Marine catalogues...

**Comment by Mad-Spy** [comment]
The "Special Issue Wargear" SEG needs to be duplicated and all the items within it made into SEs and linked into it (probably some options won't need to be there). Then that new SEG needs to be linked into the Sgt entries.

That way, you don't need to increment the main Relic count to allow the Sgt relic, but the Max 1 of each relic is retained.

It's not terribly complicated, but it's a lot of work. I had to do something similar for the Dilettante extra Relic in TSons.

Either that, or move the strat selection to the Sgt models themselves and make the selection of a Relic on them required.

**Comment by awesomedom1** [comment]
Hi team, I’ve noticed that when you give the warlord trait “artisan of war” to a captain (also tested with captain in gravis armour) and give him a relic plus a special issue wargear it gives an error that “captain has 1 too many selections from relics (maximum 1)”. It also says that the detachment has “1 too many selections from relics (maximum 2)”. 

I’m posting it here as it sounds like it may be linked to (or the same problem as) the one described above. Do you agree, or should I raise this separately?

I’m on the iOS version using the latest blood angels catalogue.

**Comment by acebaur** [comment]
It appears this is now fixed when I put the Sgt strats into the Sgt's themselves

**Comment by acebaur** [comment]
The Sgt strats are now located within the Sgt's themselves and while this is still technically possible, the CP is still being paid and the odds of it being used in this manner is now slim and the amount of work involved to fix it is not worth the effort.
