### ISSUE TITLE
Imperium - Adeptus Custodes: Shield Captain spear/axe cost

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#10818]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The shield captain is no longer 110 points but a flat 100 as the spear and ax no longer has a value

**Comment by Technoblazed** [comment]
The shield captain is 110 points base in the codex, not quite sure where you got 100 from.

**Comment by RespectableJack** [comment]
Probably thought that because on the official app he is listed at 100 points, and further the Allarus shield captain is listed at 110
![image](https://user-images.githubusercontent.com/72748875/149801069-7b933341-2aac-43e8-8cb5-9a00a4ca72fd.png)
![image](https://user-images.githubusercontent.com/72748875/149801098-b7fba2dc-8713-46d6-a738-d8889f8f4867.png)
