### ISSUE TITLE
Imperium - Astra Militarum: Master of Ordnance Request

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11062]
**File:** Warhammer 40,000.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Astra Militarum: Master of Ordnance. 
I am able to tick a box to display his orders. However, I can find no mention, nor keyword anywere that would allow him to give orders, other than if I made him a warlord and then gave him the specific trait that would grant him the voice of command ability. 

However, should the option to display orders not be hidden until that warlord trait has been selected? 

Commissars are also able to take this trait if made a warlord, yet they do not have the option to display orders without any warlord traits. 

So my question is: Is this a bug of some kind or have I completely missed an errata or something else that allows the MoO to give orders to regiment units? 
(I would love for the MoO to be able to do so. but at the same time, I also want to follow the updated and correct rules.) 

Thank you.

**Comment by williamcaw** [comment]
this is currently being investigated since February first. there is a tone of data to reviewed in the "Imperium - Astra Militarum.cat" .
the logic Master of Ordnance comes from two keywords Character and Officer to issue orders.

Commissars, Master of Ordnance, use your finger to tap on the dot at  the bottom of the screen while selecting Master of Ordnance or a Commissar for a warlord trait  
    
do refresh your data as of march 10 the current file is named Release v9.3.7 , Warhammer 40,000: The Space Elves have been on a bug hunt, Iyanden rejoices...
