### ISSUE TITLE
Imperium - Blood Angels: "Relics of the Chapter" should be "Relic of the Chapter"

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11185]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** The Power Sword for the Death Company Intercessor with a melee weapon should be 5 points.

Also, Stratagem: Relic of the Chapter is still incorrectly named Stratagem: Relic(S) of the Chapter.

**Comment by AbonShell** [comment]
![SmartSelect_20220426-181723](https://user-images.githubusercontent.com/20672472/165401997-32e39b1d-dbc4-40f3-8a1f-4f10ba1bc6d7.jpg)
They are 5 pts. But yes there is technically the typo

**Comment by zeoevil** [comment]
The bug occurs when you equip the squad with Astartes chainswords and heavy bolt pistols. When you choose an intercessor with a melee weapon, the power sword is 0 points. Also, I'm pretty sure the FAQ changed them to work just like assault intercessors i.e. one model that works just like a intercessor sergeant. So that needs to be fixed as well.

**Comment by AbonShell** [comment]
Make a new bug report for each issue. That should have been in the report in the firstplace
