### ISSUE TITLE
Imperium - Adeptus Custodes: QoL requests

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11676]
**File:** Imperium - Adeptus Custodes.catz

**BattleScribe version:** 2.03.22

**Platform:** Windows

**Dropbox:** No

**Description:** I would like to ask some requests.

The Praetorian Plate doesn't add 1 to the Toughness characteristic automatically.
Can someone programm it for do it automatically?

There is 2 ways for change a unit.
The new one and the old one.
The new one is good, but the old one is a bit awkward.
Can someone programm it for make all units with the new way?

Custodian Guard with Adrasite and Pyrithite Spears don't have Objective Secured and they should have it.

Aquilon Custodians don't have Teleport Homer and they should have it.

Thank you for your amazing work.

PD: Sorry about my poor english.

**Comment by chituchituchitu** [comment]
![1](https://user-images.githubusercontent.com/109617823/179807055-fd7eda5e-062e-4c73-a993-366d2c568eec.png)
![2](https://user-images.githubusercontent.com/109617823/179807057-6e6e769c-b264-439c-a98e-16a5c4786150.png)
![3](https://user-images.githubusercontent.com/109617823/179807060-c1dece66-5aa3-4e94-9ab4-265635113bf1.png)
![4](https://user-images.githubusercontent.com/109617823/179807061-50bf9cbe-66d3-4243-b5d7-108d7c8f8829.png)

Image 1 is the new way.
Images 2, 3 and 4 are the old way.

**Comment by Thairne** [comment]
The new implementation is not really feasible for aquilon custodians. That unit would have 12 different possible loadouts. The old way is preferred for those.

**Comment by chituchituchitu** [comment]
Is there any possibility of making two option boxes so that there are not so many options and everything can be done with the new form?

An idea would be like this:
![0](https://user-images.githubusercontent.com/109617823/183044720-dc52e776-3d34-4600-b28e-d76db3d8949c.jpg)

Or another idea would be like this:
![00](https://user-images.githubusercontent.com/109617823/183045197-8f7b2055-ca5e-4023-b306-dade61e3f07f.jpg)

**Comment by Thairne** [comment]
No it would not, since misericordias are on a model level, not on a unit level.
There's zero incentive in the rules to NOT have a misericordia, that doesnt change though that it is an individual selection.
Just imagine a misericordia costing 1 pt (or 3, like it earlier did) and you'll understand why thats not an option.

**Comment by chituchituchitu** [comment]
Ok, thanks for answering :).

**Comment by chituchituchitu** [comment]
In the 1st image it's not an option, but in the 2nd maybe it could be.

**Comment by chituchituchitu** [comment]
I was just thinking of doing it in a cool and effective way :).

**Comment by Thairne** [comment]
well again no, for the same reason ;)
What if one of your bikes dies? Which one has the misericordia? The one with the destructor, the one with the las pulsor or the bolt cannon?
there very often is an actual reason for how the data is laid out, be it game rules or battlescribe rules.

**Comment by chituchituchitu** [comment]
But you already know which one has mercy and which one doesn't.

I understand that it cannot be done for the reasons you give, a pity :(.
