### ISSUE TITLE
Daemon Prince (Daemons) can't use god specific relic strats without a greater daemon

### ISSUE THREAD

**Issue by Thor-axetheImpaler** [BSData/wh40k-9e#11855]
1. Create a detachment with a Daemon Prince
2. Attempt to give DP a relic using God Specific stratagem (for example Relics of the Great Garden)
3. ????
4. Failure
5. Add a Greater Daemon to the Detachment
6. ???
7. Profit!

**Comment by acebaur** [comment]
It's already been fixed, update your data

**Comment by Thor-axetheImpaler** [comment]
Oops sorry!

**Comment by Mad-Spy** [comment]
I'm not sure what you're actually reporting here, as your repro steps aren't very clear. 

I'm not sure how adding a Greater Daemon would have allowed you to select one of the God Relic strats on a DPoC. The only strat you could possibly have added would have been the Nephilim Relic strat, after adding a Warlord to your Roster. The other stratagems didn't even exist as far as the DPoC was concerned. Is that what you meant you were doing?

Anyway, as @acebaur says, it's fixed in the current release. You just need to select the DPoC's Allegiance.
