### ISSUE TITLE
Leagues of Votann - After picking custom Ancestral Judgment you can't deselect it on mobile

### ISSUE THREAD

**Issue by Dragdord** [BSData/wh40k-9e#11886]
After picking custom ancestral judgment you can't properly switch league to a named ones

1. Take Established League
2. Choose custom ancestral judgment

Screenshot
![image](https://user-images.githubusercontent.com/20326286/192151682-e586a7f4-ee8f-4b9d-8f21-1b9e38dd36ae.png)

**Comment by Mad-Spy** [comment]
That's not how League Affiliated works as far as I understand it. 

Ancestral Judgements are still Customs, so you don't get to pick an Ancestral Judgement separately RAW, because taking League Affiliated prevents you from taking any other Customs from the Established Leagues list.

The only "benefit" of League Affiliated is that you get to legally call yourself "DEEP ROCK GALACTIC" while using Kronus Hegemony rules, for example.

Although it's possible that the _intent_ was for it to work as you describe, it's currently not legal.

**Comment by Dragdord** [comment]
No, you must have misunderstood me. The problem is that if I choose custom ancestral judgment I then can't take the regular league back. In those cases, the option appears to be none, so you can remove the custom ancestral judgment and take the regular league. But you have to delete the league from the configuration and add it again and then choose the one you wan

**Comment by Mad-Spy** [comment]
Ok, I see what you're saying now. It wasn't obvious from your initial post. I thought you were deliberately choosing a normal League after picking a custom Judgement. Maybe some of your repro steps got lost?

If you're on desktop, you should be able to just delete it in the central pane.
