### ISSUE TITLE
Chaos - Daemons: Daemon Princes should be hidden in DoB Detachments

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#11921]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** (Bug 1: not sure) If you set Army of Renown - Disciples of Be'lakor in a supreme Command detachment (with Be'lakor as warlord) it applies to all other detachments.

(Bug 2) In my case, I can include in a batallion detachment a Lord of Change and a Daemon Prince with Disciples of Be'lakor keyword. I think it contradicts the restriccion 2 and 3 for "Disciples of Be'lakor" in codex

**Comment by Mad-Spy** [comment]
1. If you're taking a DoB AoR, every Detachment in your army needs to be valid for that AoR. Not a bug.
2. You can only put a LoC in an DoB Detachment if you add that model before you add the AoR selection. Otherwise it is hidden. Eitherway, you'll get a validation message if you do. Daemon Princes should be hidden though.
