### ISSUE TITLE
Aeldari - Drukhari: Haemonculus Upgrade SSEG acts differently to other HQs

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#12040]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Create Drukhari Roster.
Select Obsession Realspace Raid
Add
Archon
Succubus
Haemunculus

You then can select Upgrade for Archon and Succubus, but NOT for Haemunculus, whis is a bug.

**Comment by Mad-Spy** [comment]
The problem here is that the Alchemical Maestro upgrades for the Haemonculus are _hidden_ until a Coven is selected, while the upgrades for the Succubus and Archon are all visible and then invalid ones get hidden when a subfaction is selected.

Thus, people who don't understand that the rules require you to select subfactions in a Realspace Raid get confused.

Ideally, it either needs the Haemonculus to match the others, or for selecting a Realspace Raid to force you to select subfactions.
