### ISSUE TITLE
ARMY OF RENOWN: CULT OF THE CRYPTEK - Missing Illuminor Szeras

### ISSUE THREAD

**Issue by CyberBlueJackal** [BSData/wh40k-9e#12350]
**Is your feature request related to a problem? Please describe.**
When building a Cult of Cryptek army list - Key HQ unit <ILLUMINOR SZERAS> missing from data log on Battlescribe - Szeras is a Cryptek unit & a Dynastic Agent but Games Workshop have **CONFIRMED** that he is Firstly as Cryptek then a Dynastic Agent to the Silent King (Chat log from Games Workshop with Date stamp added)

**Describe the solution you'd like**
Illuminor Szeras added as HQ under Cult of Cryptek on Battlescribe

**Describe alternatives you've considered**
N/A

**Additional context**

![Cult of Cryptek Illuminor Szeras](https://user-images.githubusercontent.com/123464141/214275800-b40d2fce-dd00-40fb-bf99-0193084287cd.JPG)

**Comment by CyberBlueJackal** [comment]
Initial Message sent querying this rule when Cult of Cryptek first dropped attached here
![Initial Message](https://user-images.githubusercontent.com/123464141/214276597-df61aa35-65d3-42bc-ad90-d0b09c7e4f33.JPG)
###

**Comment by WindstormSCR** [comment]
Hate to say it, but we follow rules as written and published. Regardless of what the GW help line may say (because you can ask five different times and receive 5 different answers)

the cult of the cryptek AoR specifies (edit) that all models must be drawn from the same dynasty. Szeras does not have a selectable keyword, making him an invalid selection.
