### ISSUE TITLE
Leagues of Votann - Boarding Action - Brokhyr Iron Master too many character error

### ISSUE THREAD

**Issue by fallingbear** [BSData/wh40k-9e#12370]
![image](https://user-images.githubusercontent.com/611341/214751222-5ff5ac53-4b8a-4271-93af-04f9c430dd43.png)

When adding the Iron Master to a boarding action list, the error "has 1 too many selections from Character".

**Comment by Mad-Spy** [comment]
That is because, as per the unit's data sheet, there are 2 CHARACTER models in that unit; the Brokhyr and the Ironkin. You're only allowed one CHARACTER model in a Boarding Patrol by default.

GW need to FAQ it to allow him regardless of that fact. 
I suggest emailing the FAQ email to ask them to do so. For now, you'll just have to ignore the error.
