### ISSUE TITLE
Imperium - Space Wolves: A Trophy Bestowed not allowing Successor Chapters to take relics.

### ISSUE THREAD

**Issue by sOlOnOmO** [BSData/wh40k-9e#12612]
Adding "A trophy Bestowed" does not a Space Wolves Successor Chapter character access to Relics of the Fang relics.

Add a character to your list
Make them your warlord
Add "A Trophy Bestowed" to your list
See that you don't have access to relics on character

Expected outcome:
Access to Relics of the Fang on a Space Wolves Successor Chapter.

**Comment by acebaur** [comment]
What chapter is this?

**Comment by AbonShell** [comment]
Fix for issue is to change the scope of the relic SSEG hide to be Force instead of Parent for A Trophy Bestowed

**Comment by sOlOnOmO** [comment]
This is Space Wolves in the successor chapter

**Comment by sOlOnOmO** [comment]
Hello, and sorry I do not understand. Basically "A trophy bestowed" Should
just be the 1 CP and no extra CP cost for the "Relic" Stratagem. It's
giving me an error and forcing me to spend the extra CP basically.

**Comment by Mad-Spy** [comment]
A Trophy Bestowed allows you to take a Relic of the Fang _instead_ of a normal Relic.

![image](https://user-images.githubusercontent.com/29306451/226881285-9e4c7e8a-e12a-4f19-85f6-0af43f5949f6.png)

If the model is not eligible to take a Relic, you can't give it something instead of that non-existent Relic.

You do have to pay 2CP.

**Comment by sOlOnOmO** [comment]
Oh okay! Thank you for the clarification! So it does cost 2CP in total. Got
it! I appreciate your time! Have a great week
