### ISSUE TITLE
Bug report: Imperium - Iron Hands.catz Dreadnaught Character does not count as Character for Elite Slot

### ISSUE THREAD

**Issue by vhp17099** [BSData/wh40k-9e#12621]
Hi, this is an Iron Hands only issue I think:

According to the new Arks Detachment, Elite Characters do not count for the standard Elite slots. If you make a Dreadnaught a Character  via March of the Ancients he is still counting for the standard Elite slots but should count for the Elite Characters instead.

**Comment by acebaur** [comment]
He can't be a elite character. Here is the breakdown of why
In order to make the Dreadnought a character, you need to use the March of the Ancients stratagem.
In order to use that stratagem, you need to have an Iron Hands detachment and to have also picked a character as your Warlord.
In order to pick your Warlord, we need to first check the timing on the Matched Play rules. Step 2 (Muster Armies) says use the Open Play rules on Page 238 of the Core Rulebook. The Open Play rules then say you need to have mustered your army to be able to choose the Warlord.
In order to have fully mustered your army via the Battle-Forged rules, all units must be allocated to detachments and are locked into the appropriate Battlefield Role slots.

If any step of that is missed, your Dreadnought being in a character Elite slot is illegal.

**Comment by vhp17099** [comment]
Even though I will not argue with the logic you posted, events like the Manchester 40k Super Major do not agree with your argument.

Check Innes Wilson and Brian Sepp list from the Top5 here: https://listbot40k.herokuapp.com/

There are a lot more cases too.

**Comment by ThePants999** [comment]
I *will* argue with that logic @acebaur :)

You didn't specify which mission pack you were quoting from, but Step 2 in Arks of Omen: Grand Tournament does _not_ reference the Open Play rules. In fact, none of the Grand Tournament mission packs have had that reference. It sounds like you were quoting from the Eternal War mission pack - the core rulebook does not contain "Matched Play" rules, it contains an explanation of the Matched Play _concept_ (page 279), and then it contains a specific Matched Play mission pack, Eternal War, that is completely irrelevant if you're playing a different mission pack.

So in Arks (and Nephilim, and Nachmund, and GT21, and GT20), the only guidance is to follow the core rules, which only talk about warlord selection on page 251, which has no timing at all. (The numbers on that page are not order of steps, otherwise filling in the warlord traits in "step" 4 would be rather difficult before selecting your warlord in "step" 8 😊)

It's frustrating that GW haven't made this explicit, but there are many ways to tie oneself in knots trying to figure out the order of list building steps, while everything actually drops out surprisingly neatly if you instead assume that there _is_ no order other than the timing specified in stratagems (e.g. "after selecting your WARLORD"). You just have to slap a bunch of units together into detachments, pick a warlord, use your strats, and then finally validate that you've complied with all the rules governing legal Battle-forged armies - including how many of each battlefield role you have in each detachment.

"Slots" is an unfortunately misleading word for them to use when describing detachments, because it causes people to think in terms of placing units into slots, when it's really just syntactic sugar over limits. Quoting the rules:

> BATTLEFIELD ROLE SLOTS
> This section of a Detachment’s rules lists the minimum and maximum number of units in each Battlefield Role that you must or can include in the Detachment.

The fact that an Arks detachment has 3 Elite slots and 3 Elite (CHARACTER units only) slots means that, when you come to check the legality of your detachment, you must have a minimum of 0 and a maximum of 3 Elite units plus a minimum of 0 and a maximum of 3 Elite CHARACTER units.

I obviously can't claim this is definitive because GW have not seen fit to write definitive rules ☹ but every tournament I've asked (WTC, UKTC and Goonhammer IRL, and Alpha League, Try Hard and Copenhammer on TTS) have ruled in favour of this working, so this Battlescribe validation is in practice proving to be a barrier not a help.

**Comment by vhp17099** [comment]
> I _will_ argue with that logic @acebaur :)
> 
> You didn't specify which mission pack you were quoting from, but Step 2 in Arks of Omen: Grand Tournament does _not_ reference the Open Play rules. In fact, none of the Grand Tournament mission packs have had that reference. It sounds like you were quoting from the Eternal War mission pack - the core rulebook does not contain "Matched Play" rules, it contains an explanation of the Matched Play _concept_ (page 279), and then it contains a specific Matched Play mission pack, Eternal War, that is completely irrelevant if you're playing a different mission pack.
> 
> So in Arks (and Nephilim, and Nachmund, and GT21, and GT20), the only guidance is to follow the core rules, which only talk about warlord selection on page 251, which has no timing at all. (The numbers on that page are not order of steps, otherwise filling in the warlord traits in "step" 4 would be rather difficult before selecting your warlord in "step" 8 😊)
> 
> It's frustrating that GW haven't made this explicit, but there are many ways to tie oneself in knots trying to figure out the order of list building steps, while everything actually drops out surprisingly neatly if you instead assume that there _is_ no order other than the timing specified in stratagems (e.g. "after selecting your WARLORD"). You just have to slap a bunch of units together into detachments, pick a warlord, use your strats, and then finally validate that you've complied with all the rules governing legal Battle-forged armies - including how many of each battlefield role you have in each detachment.
> 
> "Slots" is an unfortunately misleading word for them to use when describing detachments, because it causes people to think in terms of placing units into slots, when it's really just syntactic sugar over limits. Quoting the rules:
> 
> > BATTLEFIELD ROLE SLOTS
> > This section of a Detachment’s rules lists the minimum and maximum number of units in each Battlefield Role that you must or can include in the Detachment.
> 
> The fact that an Arks detachment has 3 Elite slots and 3 Elite (CHARACTER units only) slots means that, when you come to check the legality of your detachment, you must have a minimum of 0 and a maximum of 3 Elite units plus a minimum of 0 and a maximum of 3 Elite CHARACTER units.
> 
> I obviously can't claim this is definitive because GW have not seen fit to write definitive rules ☹ but every tournament I've asked (WTC, UKTC and Goonhammer IRL, and Alpha League, Try Hard and Copenhammer on TTS) have ruled in favour of this working, so this Battlescribe validation is in practice proving to be a barrier not a help.

@ThePants999 I would like to press this more, but I'm not sure if this is the proper way to do it. Since you are a contributor here maybe you know a better way?

**Comment by ThePants999** [comment]
Nothing to do AFAIK but wait for @acebaur 's response.
