### ISSUE TITLE
Primaris Hellblaster Costs

### ISSUE THREAD

**Issue by newLoki** [BSData/wh40k-9e#259]
**File/Catalogue:**  Imperium - Space Marines.cat

**BattleScribe version:** 2.01.

**Platform:** Mac

**Dropbox:** No

**Description:** The Primaris Hellblaster Squad is only 10 PL but 12 PL in the file.

**Comment by MaverickIV** [comment]
The Primaris Hellblaster Squad PL cost in the Dark Angels list is also incorect: only 6PL where it should be 12.

Where are you getting your PL ? Because in my Index it is charged at 12 PL. Are you using the "Primaris Index" from the starter box (which I do not have to compare) ? Because they have shown a picture of a profile at 10 PL on their community site but I do not know where it comes from.

**Comment by flakpanda** [comment]
The PL 10 version comes from the starter primaris pamphlet. They are PL 12
in the index.

**Comment by newLoki** [comment]
@flakpanda Ok, good to know that the starter box is incorrect :D
Should this issue be closed or stay open to fix what @MaverickIV mentioned:

> The Primaris Hellblaster Squad PL cost in the Dark Angels list is also incorect: only 6PL where it should be 12.
