### ISSUE TITLE
Imperium - Space Wolves - Strange bug

### ISSUE THREAD

**Issue by IronWulfen88** [BSData/wh40k-9e#330]
**File/Catalogue:** 

**BattleScribe version:** 2.01.02

**Platform:** Android

**Dropbox** Yes
Something strange is happeningoing. I have two packs of wulfen and I gave them certain weapons and the other pack got them too before I could even add them. Same for my two packs of grey hunters when I added the chains words. Though the grey hunter pack leaders didn't copy.

**Comment by Gnofry** [comment]
Going to comment instead of creating a new issue.

The number of Grey Hunters w/ Bolt Pistol is collective across all Grey Hunter squads. Increment 1 squad also increments all other squads.

The number of special weapons isn't being checked quite properly. 5 GH w/ BP + 2 w/ PG + WGPL + GHPL +GH / Plasma Pistol triggers max 1 of GH w/ Special weapon error. I think the issue is with it not counting the WGPL.

**Comment by IronWulfen88** [comment]
Only problem is I'm not running packs of the same size for all my lista
