### ISSUE TITLE
Imperium -  Astra Militarum issues

### ISSUE THREAD

**Issue by bowgs** [BSData/wh40k-9e#339]
**File/Catalogue:** Astra Militarum v18

**BattleScribe version:** 2.01.

**Platform:** Windows/Android

**Dropbox:** No

**Description:** 

The catalogue is very usable now, but there are a few low priority issues remaining

### Veterans
- [x] Count as elites AND troops for detachment purposes.  Should only be elites

### Militarum Tempestus Scions
- [x] The label above the Scions gives the wrong count.  For instance take this full-strength squad - 1 Tempestor, 4 Scions w/special weapons, 1 Scion w/voxcaster and 4 Scions w/hotshot lasguns.  This squad can now be created and validated, and has the right costs.  The only problem is it says "10 x Scions" in the label, when really it is 9 x Scions and a Tempestor.  This is VERY low priority as the points and validation are correct and the profile looks fine.

**Comment by Eerieuk** [comment]
As above this issue is a low priority issue.
Wouls it be possible for the veterans be setup to show a condensed list like the infantry squad. Default  Infantry squad shows 9x guardsmen and a sergeant, were as the veterans shows up a 9 individuals veterans and a sergeant.
Again really appreciate the effort and time being put in.
![vet](https://user-images.githubusercontent.com/29521496/27390280-cf55ef54-5698-11e7-9cd3-9e5c7b8f4f5f.png)

**Comment by alphalas** [comment]
@eerieuk no - because each vet can take separate weapons.

**Comment by alphalas** [comment]
@bowgs @genwilhelm figured out what the count problem is - it's counting not the tempestor, but the grenades entry. I'll fix it in a half-hour or so

**Comment by GenWilhelm** [comment]
@alphalas in a case where there's only a handful of valid configurations, is it not better to make each configuration a separate entry - ie. Veteran w/ Lagsun, Veteran w/ Shotgun?

**Comment by Eerieuk** [comment]
Similar to how 7th ed file was
![vet2](https://user-images.githubusercontent.com/29521496/27392000-570ee3f2-569d-11e7-9af4-c78bbefa454d.png)
