### ISSUE TITLE
CAT - Chaos - Heretics and Renegades

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-9e#381]

**Comment by Penallegion** [comment]
Short list so far:
Colossus Bombard - missing points
Colossus Bombard - no default wargear
Colossus Bombard - missing Explodes
Colossus Bombard - missing Smoke Launchers
Colossus Bombard - missing Vehicle Squadron
Colossus Bombard - Pintle mount not min/max 1 choice
Salamander Scout Tank - change Scout vehicle to profile ability instead of rule
Arvus Lighter - weapon choices should be entry group, max 1, have "two hellstrike missiles" and "two twin heavy stubbers" as selections with nested entry for each, with min/max 2 constraints
Valkyrie - no default wargear selected
Weapon point cost fixes
Autocannon 15 pts not 20
Heavy bolter 8 pts not 10
Twin Autocannon 25 pts not 33

**Comment by Penallegion** [comment]
Use more shared profiles/entries contra rules on units

**Comment by cartag** [comment]
- [ ] Malcador Defender shouldn't be nested like it is. Root level should be model, not unit with one model.
- [ ] Malcador Defender side weapons should be entry group with "2x weapon" as the options, nested entry with min/max 2 on weapons.

**Comment by cartag** [comment]
- [ ] Renegade Weapon Team heavy weapon should be entry group, not a list of checkboxes.
- [ ] Renegade Weapon Team heavy weapon set to max 0
- [ ] Renegade Weapon Team missing default wargear
- [ ] Plague Ogryn PL not incrementing properly
- [ ] Plague Ogryns are 25 pts, not 26.

**Comment by Penallegion** [comment]
Closed most of them today, still missing Twin autocannon but will have a go one of the days, commented what hasn't been corrected

**Comment by FarseerVeraenthis** [comment]
Since this CAT has been released, can we close this issue now?

**Comment by Penallegion** [comment]
yeah will just copy the last issue and manke new bug report for R&H
