### ISSUE TITLE
Chaos Space marines a couple of bugs

### ISSUE THREAD

**Issue by Penallegion** [BSData/wh40k-9e#526]
**File/Catalogue:** 
**BattleScribe version:** 2.01.
**Description:** Detailed issue description.

- [x] Dark Apostle is missing Dark zealotry and Demagogue abilities

- [ ] mark of khorne missing description

- [x] cultists can't take mark

- [ ] Chosen Doesn't decrement Bolt pistol if you replace weapon
![plasma](https://user-images.githubusercontent.com/25779557/27594531-4f7d15d4-5b5a-11e7-821e-c02d51128522.png)

**Comment by cartag** [comment]
Marks currently don't do anything and have no description. What do you want me to list? 

Chosen wont' decrement, did you miss the part where it says "Replace bolt pistol with..." It's the same way with pretty much any unit. I would assume our end users are intelligent enough to figure out what weapons their models have.

**Comment by Penallegion** [comment]
Okay but a TO would probably not want to see a chosen with boltguns plasma guns chainsword and grenades since it's not a legal choice. 
Why don't you just remove the boltgum from default and put it with the replacements calling it gun selection or something. That way you can make a legal output

**Comment by cartag** [comment]
TOs should be used to seeing that format because it's been that way a long while now, all through 7th at least I can vouch for. I would have to rework the entire file to change everything that has even the slightest weapon choices to that, and that's not happening. This isn't a Chosen thing, it would be the same for every infantry unit that has options.
