### ISSUE TITLE
Imperium - Legion of the Damned - Why is this a separate CAT?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#571]
**File:** Imperium - Legion of the Damned.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** Hi. You should include this repository in the Imperium - Space Marines one (like, for example, you already have included a Black Templar's Crusader Squad or the Captain Lysander...). Thanks!

**Comment by FarseerVeraenthis** [comment]
The decision was taken to have Legion of the Damned as a separate CAT so that anyone who wants to use them with one of the other named legions that are not included in the SM CAT can do so, without having to pull the whole SM CAT for a single datasheet.
In reality, having these guys as a separate CAT reduces the size of every other Imperium CAT (because they don't have to include LotD) and makes it easier to add a unit of Legionnaires to your Imperium Army.

**Comment by marneuscalgar** [comment]
Ok, but the problem is that, in this manner, is not possible take a LotD unit as a valid elité choice in a detachment in which the other units comes from a SM CAT (or a DA, BA, Astra Militarum CAT, that is the same...): in 8th ed., indeed, units in the same detachment only have to share a single faction keyword (that can be even just IMPERIUM or ADEPTUS ASTARTES...)!

**Comment by marneuscalgar** [comment]
![clipboard02](https://user-images.githubusercontent.com/8770199/27749731-010d6ad4-5dd5-11e7-9475-860b8284b4c8.jpg)

**Comment by flakpanda** [comment]
Please refer to our will page about creating a detachment with multiple
catalogs.

**Comment by alphalas** [comment]
https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions

**Comment by marneuscalgar** [comment]
Oh, great work! Thanks!!!
