### ISSUE TITLE
Imperium - Dark Angels: Can't find Primaris Master weapon options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7292]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The Primaris Master does not have an option for the additional power sword as described in the Psychic Awakening datasheet.

**Comment by Mad-Spy** [comment]
You need to drill-down into the auto-bolt rifle and bolt pistol option. You'll notice that it has an orange tab on the left, rather than a grey one. That is how BS denotes that an item has sub-options. Tap on the name (not the radio button on the right) to get to the options to swap rifle or add a melee weapon.
