### ISSUE TITLE
Astra Militarum - Heavy Bolter cost incorect on manticory

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#7457]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Heavy bolter still costs 8 points instead of 15 on the manticore, and possibly other vehicles "I haven't checked all of them"

**Comment by williamcaw** [comment]
Heavy bolter is still 15 chapter approve 2020 page 46

**Comment by GuillermoDiazGarcia** [comment]
Yes, that's the point of the bug report (I did it without logging in for some reason). It still costs 8 on battlescribe in the manticore though, when it should indeed be 15 (that's what I wrote)

Also, since I'm here, flamers cost 6 instead of 5 on Scions. It seems to be corrected in every other unit though

**Comment by fuckingenglish** [comment]
Fw has the heavy flamer and bolter for 15
