### ISSUE TITLE
Orks - Kustom Force Field pts incorrect

### ISSUE THREAD

**Issue by mxcpotato** [BSData/wh40k-9e#7656]
**File/Catalogue:** Orks.catz

**BattleScribe version:** 2.03.05
**Description:** Big Mek with Kustom Force Field is at 75pts and it should be 60pts.

**Comment by spartanbs** [comment]
Points cost and rules for this model has been FAQ'd as of 27/07/2020:

Page 71 – Big Mek with Kustom Force Field: Change this model’s Power Rating to 4 and points value to 75. 

Page 71 – Big Mek with Kustom Force Field: Change this ability to read:‘Kustom Force Field: Friendly Ork units have a 5+ invulnerable save against ranged attacks whilst they are wholly within 9" of this model. While this model is embarked, the model transporting it has a 5+ invulnerable save against ranged attacks.

**Comment by Velgarn** [comment]
There is still some confusion if the final point should be 75 or 60 because the FAQ came after the FMM but the FAQ for SotB where supposed to came out before 9th edition dropped. 
So far in the Official App the points are still 60 but also they didn't even fixed the KFF description, so when they actually upgrade it that should indicate which cost is correct then.
My suggestion is to keep this Issue open untill we get a clear answer

**Comment by tag8833** [comment]
The points are 75.   The FAQ is after MFM.   If you update your data files you will see the new points.
