### ISSUE TITLE
Sisters of Silence should be available in Adeptus Custodes detachments

### ISSUE THREAD

**Issue by sewalshmsft** [BSData/wh40k-9e#8092]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Please add Sisters of Silence to Adeptus Custodes detachments. The interpretation in issue #7250 is incorrect. According to the War of the Spider, Sisters of Silence added to Custodes detachment does not prevent the army from being Battle Forged. See attached picture.

![20200908_181502736_iOS](https://user-images.githubusercontent.com/24483326/92514075-58522180-f1df-11ea-9ff5-d2cf4233d31f.jpg)

**Comment by Valorcalls** [comment]
#7250 is correct. The unit card for Aleya and Valerian don't meet the qualifications for these rules, they can only legally be included in a Imperium detachment since that is their only faction keyword.

As for adding them to the detachment, are you having an issue nesting the sisters forces under a Custodes detachment?

**Comment by Mad-Spy** [comment]
You can add a child Detachment of Sisters like this - https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions to include Sisters units in your Custodes Detachment.

Valerian and Aleya not being allowed is a separate issue due to that unit not having appropriate **Faction** keywords.
