### ISSUE TITLE
Missing Formation/Troop Unit Type In Deathwatch

### ISSUE THREAD

**Issue by gi-nelson** [BSData/wh40k-9e#8267]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by gi-nelson** [comment]
So I went to add in Kill Team cassius as a troop formation in my Death watch Army... but they are nowhere to be found. After much investigation I have discovered that many people assume that they cannot be used, unless split apart or modified, in a WH40K Army... That is not the case, as GW published special rules for them that have not been revoked or superseded... I would make the change in the editor, but am unsure how - please advise how this change can be made to happen - or some basic instructions of how i can add them? Here is the GW pub for verification https://www.games-workshop.com/resources/PDF/Deathwatch/40k-rules-deathwatch-en.pdf

**Comment by Technoblazed** [comment]
Will be completed in https://github.com/BSData/wh40k/issues/8256.

**Comment by MrRWJP** [comment]
> So I went to add in Kill Team cassius as a troop formation in my Death watch Army... but they are nowhere to be found. After much investigation I have discovered that many people assume that they cannot be used, unless split apart or modified, in a WH40K Army... That is not the case, as GW published special rules for them that have not been revoked or superseded... I would make the change in the editor, but am unsure how - please advise how this change can be made to happen - or some basic instructions of how i can add them? Here is the GW pub for verification https://www.games-workshop.com/resources/PDF/Deathwatch/40k-rules-deathwatch-en.pdf

That PDF is for 7th Edition and is no longer valid. The stat lines for the units are no longer correct for the stats used in 8th or 9th. That PDF was revoked when 8th was launched because the stat lines are not compatible.

Ironically enough though, despite being wrong about the source of the rules, you are still right, Kill Team Cassius does have rules in 9th that were released a couple of days ago. They are available here: https://www.warhammer-community.com/wp-content/uploads/2020/10/rLCZMRuhVxZsxTuV.pdf
