### ISSUE TITLE
Necrons - two issues i found while testing the new file

### ISSUE THREAD

**Issue by Tobbns** [BSData/wh40k-9e#8296]
*Sry if i don't follow any rules here - i'm new to this*

When adding Skorpekh Destroyers, adding a forth Destroyer correctly rises the PL of the unit to 10, but when there are 5 or more it is back down to 5 PL. The Points are calculated correctly though.

Adding multiple Cryptecs (Like Technomancer, Plasmancer etc.) as one HQ Slot according to their Dynastic Advisors Rule does not work, the Detachment notifies about an issue of too many HQs. This is true for any combination of Cryptecs as far is a tried.

**Comment by Mad-Spy** [comment]
After the first Cryptek, you need to add them from the No Force Org Slot group, not HQ.

**Comment by DrTobogganMD** [comment]
Both fixed for next push. At Least should've been used - I was using equal to 4 models. As for crypteks, yes they should be in the No Force Org. It's not very self explanatory but it's how the implementation had to be done in order to not count HQ slots.  I've added the following text at the end of the Dynastic Advisors ability to help ease a bit of confusion: [These are located in the No Force Org section of Battlescribe]
