### ISSUE TITLE
Eldar/Ynnari Psychic powers incorrect.

### ISSUE THREAD

**Issue by Mark-La1905** [BSData/wh40k-9e#8329]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Android

**Dropbox:** No

When you add a psyker to a ynnari detatchment they loose thier 'Runes of Fortune' powers.

The Ynnari index says "Ynnari psykers must generate thier powers from the Revenant discipline instead of from the Runes of Battle, Runes of Fate or Phantasmancy discipline"

Since psychic awakening they have also had powers under the Runes of Fortune discipline and with RAW they should retain them when becoming Ynnari.. e.g. they shouldnt lose smite, ghostwalk etc which are choices under Runes of Fortune.

Im not aware of any FAQ that says they loose them and if it doesnt exist they shouldn't. e.g. a ynnari spiritseer should be able to choose one power from Runes of Fortune and one power from from the Revenent discipline (which replaces thier Runes of Battle power)

If there is a FAQ that Im not aware of that says all powers must come from the Revenent discipline then they should pick two powers from the Revenant discipline, one to replace thier Rune of Fortune power and one to replace thier Rune of Battle power. 

If there is such a FAQ then the Wraithseer might also be wrong when added to a ynnari detatchment, currently it keeps its 3 specific powers and such a FAQ if it exists and depending on wording might mean it picks 3 powers from the Revenant discipline instead.....

**Comment by Mad-Spy** [comment]
There's no FAQ because as per the rules for Runes of Fortune on p47 of Phoenix Rising, only `<CRAFTWORLD> PSYKER` models can take Runes of Fortune. Ynnari Psykers do not have the `<CRAFTWORLD>` keyword, as it gets replaced by `REBORN ASURYANI`. Thus, they have Smite (which cannot be replaced because Ynnari have no rule allowing them to do so) and replace their powers from Runes of Battle or Runes of Fate with Revenant powers (Phoenix Rising, p66).

The Wraithseer does not choose its powers from Runes of Battle or Runes of Fate, and therefore retains its choice from its datasheet.
