### ISSUE TITLE
Blood Angels - Sanguinary Priest Abilities still showing <CHAPTER> when should be restricted to Blood Angels

### ISSUE THREAD

**Issue by rylok3** [BSData/wh40k-9e#8407]
**File/Catalogue:** Blood Angels revision 195

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Admittedly SUPER nitpicky, but the language on Sanguinary Priest should be updated, as it only effects Blood Angels.

Current language:
_Combat Restoritives | At the end of your Movement phase, this model can heal one friendly `<CHAPTER>` INFANTRY or `<CHAPTER>` BIKER model whose unit is within 3" of it. That model regains up to D3 lost wounds. Each model can only be healed once per turn._

Actual language from FAQ PDF on WarCom:
**Combat Restoratives: At the end of your Movement phase, this model can heal one friendly Blood Angels Infantry or Blood Angels Biker model whose unit is within 3" of it. That model regains up to D3 lost wounds. Each model can only be healed once per turn.**

Also same with Narthecium [Aura] (which should be changed to (Aura) for consistency).

Current language:
_Narthecium [Aura] | While a friendly `<CHAPTER>` INFANTRY or `<CHAPTER>` BIKER unit is within 3" of this model, each time a model in that unit would lose a wound, roll one D6; on a 6, that wound is not lost._

Actual language from FAQ PDF on WarCom:
**Narthecium (Aura): While a friendly Blood Angels Infantry or Blood Angels Biker unit is within 3" of this model, each time a model in that unit would lose a wound, roll one D6: on a 6, that wound is not lost.**

**Comment by ASHC2486** [comment]
I suspect it was intentional because BA have successor chapter rules.

From the FAQ: 
For example, If you include a Sanguinary Priest in your army, and you decide it is from the Lamenters Chapter, its Blood Angels keyword becomes Lamenters and its Narthecium ability reads ‘While a friendly Lamenters Infantry or Lamenters Biker unit is within 6" of this model, each time a model in that unit would lose a wound, roll one D6: on a 6, that wound is not lost.’

While saying "Blood Angels" instead of <Chapter> is more technically correct, using the <Chapter> flag allows for successor chapters to work.

**Comment by rylok3** [comment]
Agreed @ASHC2486 - but this is an issue to ensure the correct text is used from the WarCom updates.
