### ISSUE TITLE
Imperium - Dark Angels: Whirlwind Scorpius should be Heavy Support

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#8867]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** 1. Forged World Whirlwind scorpius should be under heavy support.
2. Talonmaster (lieutenant) unable to take Corvus Occulus (relic)

**Comment by Thairne** [comment]
Vehicles are not allowed to take relics.

**Comment by miku2020** [comment]
wrong. you can take Corvus oculus on Talonmaster. it was originally (vehicles cannot be given) but then changed without that because of corvus oculus. also note afaik this is only exception to the rule. 

> If your army is led by a Dark Angels Warlord, you can, when
> mustering your army, give one of the following Relics of Caliban
> to a Dark Angels Character model in your army instead of
> giving them a Relic from Codex: Space Marines. These are
> considered to be Chapter Relics for all rules purposes.
> 
> Named characters cannot be given any of the following Relics.
> Note that some Relics replace one of the model’s existing items
> of wargear. Where this is the case, you must, if you are using
> points values, still pay the cost of the wargear that is being
> replaced. Write down any Chapter Relics your models have on
> your army roster.

https://www.warhammer-community.com/wp-content/uploads/2019/09/dBVOuwxpsMDtr1td.pdf
