### ISSUE TITLE
Supreme Command benefit incorrect

### ISSUE THREAD

**Issue by bigjayme** [BSData/wh40k-9e#8948]
**File/Catalogue:**  Necrons v79

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Supreme Command detachments should cost 0CP and with a proper unit selected, give you +3 CP if your army includes a Battalion detachment. Currently, Supreme Command detachment costs 3CP (8th rules) and will not refund the cost of the Battalion.

**Comment by Technoblazed** [comment]
Looks like you're misreading the detachment with the SK in it. It is GIVING you back 3CP as one that's one of the abilities of the SK. The battalion will display as -3CP because that is the name of the detachment, but you are refunded the 3CP as displayed at the top.

![Image](https://i.tech-no.me/2020/12/02/201202185718.png)

**Comment by bigjayme** [comment]
Incorrect. You can see in your own example, the Supreme Command is granting +6CP. It is currently adding 3CP, and then the Detachment CP is also adding 3CP. It is still not working as intended. *corrected below*

**Comment by Technoblazed** [comment]
That's how it's done in battlescribe. The SCD gives you back the CP for the battalion detachment, then the SK gives you another 3, totally for 6.

**Comment by bigjayme** [comment]
Oh! You are correct! The SK grants +3CP, which was my own confusion. My apologies!
