### ISSUE TITLE
Tyranid Adrenal Gland/Loadout Duplication Point Cost incorrect

### ISSUE THREAD

**Issue by aurorapar** [BSData/wh40k-9e#9026]
**File/Catalogue:**
Warhammer 40,000 9th Edition v172

**BattleScribe version:** 
2.03.21

**Platform:**
Win 10 x64

**Dropbox:** 
No

**Description:** 
Duplicating a unit that has Adrenal Glands selected does not incur the cost of Adrenal Glands on the new unit created. Hive Tyrants, Mawlocs, Trygons, and Tyrannofexes all experience this bug. Hormagaunts do not. This leads me to believe it is an issue with MONSTERS specifically, or non-TROOP units. 

Step 1
Create a new unit (Hive Tyrants, Mawlocs, Trygons, or Tyrannofexes tested, does not affect Hormagaunts).

Step 2
Add Adrenal Glands.

Step 3
Duplicate unit.

Step 4
Notice point discrepancy between original and duplicate unit.

**Comment by Mad-Spy** [comment]
**Dev Note**

This is an app bug. The points modifier on the Adrenal Gland SSE is not being resolved correctly when a unit is duplicated.

The issue can be fixed by adding a direct point cost to the SSE link on the relevant units, instead of using a modifier. Whether @GenWilhelm wants to fix it or not is up to him.

**Comment by GenWilhelm** [comment]
I've put in a hacky fix for the sake of UX. Should hold us over until the codex or chapter approved, whichever comes first.
