### ISSUE TITLE
Imperium - Officio Assassinorum: Assassins can't be made the warlord

### ISSUE THREAD

**Issue by Citronnade** [BSData/wh40k-9e#9609]
**File/Catalogue:**  Imperium - Officio Assassinorum (Overall v179/9.1.20)

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** The Independent Operative ability prevents an assassin model from gaining a warlord trait, but it should not stop the model from becoming the Warlord.  Currently, Battlescribe is not allowing any assassins to become warlords, whether they are taken as part of a standalone vanguard detachment or as an agent of the imperium.

**Comment by DrTobogganMD** [comment]
I suppose you could but you'd lose any relics for your other detachments gained via strategem. You're correct though. We can add the warlord box.

**Comment by Mad-Spy** [comment]
There's no reason to add one as they can never get a WLT, nor can they take a Relic. The Warlord check box only exists because it has an effect on the model (unlocking WLTs, Relics etc)

It's the same reason we don't add Warlord checkboxes to every model, despite any model technically being eligible to be the Warlord (in most cases).
