### ISSUE TITLE
AllThingsPointyEared Branch: Drukhari Testing Results

### ISSUE THREAD

**Issue by DrRuler** [BSData/wh40k-9e#9656]
**File/Catalogue:** Drukhari.catz

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** 
Bugs:
- [x] Should "raiding forces" auto select for patrols and be deleted by user instead? Seems like the more normal use-case.
The +2 CP is only valid if you only have Patrol detachments. I've not figured out how to validate this yet. The rest is all common sense :wink: so the only reason for the selection is to refund CP's...
- [x] No Roster Error for multiple 'Master X' from same obsession in different detachments.
~I'm actually not certain this will be possible to validate properly in BS...~ <-- Got something smashed together, not pretty but it is functional 😄

**Comment by FarseerVeraenthis** [comment]
Thanks for the list, and yes, a number of those issues I am aware of and it is because I decided to get 'something' up soonest so people could start to use the new rules ASAP :smile:

Here is a list of fixed stuff:
- [x] Deadly Deceivers should be all consuming.
- [x] Dark Technomancers custom coven selected should be all consuming.
- [x] Toxin Crafters should be all consuming.
- [x] Berserk Fugue should be all consuming.
- [x] Agile Hunters is missing? Should be "All Consuming" when added.
- [x] Acrobatic Display is incorrectly marked as All Consuming
- [x] Possibly mark the all consuming ones in the radio selection? I believe Necrons does this?

- [x] Can still take Ynnari units in Drukhari, I honestly don't know if Weakling Kin allows this by RAW, I don't have a Ynnari book or play Ynnari units, but I know people were upset about it somehow.
- [x] Urien Rakarth should only have Prophets of Flesh not the < Coven > keywording too.
- [x] Urien missing Sustained by Dark Science
- [x] Drazhar missing Blades for Hire tag
- [x] Lelith is only takeable in Cult of Strife but Urien is takeable in any detachment.  One of these two things is wrong.
- [x] Lelith should only have Cult of Strife not < Wych Cult > in addition.

- [x] Kab with heavy weapon picking anything other than splinter rifle causes list error.
- [x] Kab with special weapon picking anything other than splinter rifle causes list error.
- [x] Wracks-Acothyst: should "Wrack Blade" be part of the radio select for melee weapons rather than it's own check box? Exclusivity between the checkbox and radios is working at least, just feels wrong to use it this way.
- [x] Grotesques have 12 PL even with only 3 (should be 6 until 4th added)
- [x] No way to upgrade Wracks/Kabs/Wyches to trueborn alternatives or add those special versions when a master version of an HQ is present.
- [x] By RAW the new Reaver datasheet does not stop you from putting the 1 per 3 special weapon on the Arena Champion, check codex to confirm, but I just read it several times to make sure. (As for any RAI concerns, the model itself allows you to do this and they have been trying to ease up on new people accidentally making illegal loadouts that are technically possible in their kits, see finally letting you take rifles on our kab sergeants.)
- [x] Beastmaster properly spawns in NFOS when you select a beast unit, but is marked as [Legends]
- [x] Beasts of the Arena is only eating one Fast Attack slot when I put multiple types of beast units in it.
- [x] Beasts of the Arena should probably just be an ability of the unique beast units now, unless BS won't let you restrict them properly that way.
- [x] ~~Beastmaster no longer has options for scourge or power sword in 9th.~~ It's still in the Legends document, so it does.
- [x] Beastmaster's Legends wargear options should be listed as [Legends] in the list.
- [x] Beastmaster should be 2PL not 3.
- [x] Venom missing Hovering

**Formatting:**
- [x] Should "*Random*" for the combat drug selection instead say "Random x2 (Combat Drug)" for accuracy and consistency?
- [x] On scourges the secondary words are not capitalized other than Dark Lance
- [x] Kabalites/Sybarites also have inconsistent capitalization on second words for weapons.
- [x] Same with Ravager (probably just check everything and decide which looks best, probably not needed to launch the update, just a good project for after the first update is launched.)
- [x] "Wych with *weapon*" all lower case even first word of said weapon.
- [x] "Wrack with special weapon (up to 1 for 5 models)" vs "Kabalite warrior with Heavy Weapon" vs "Kabalite Warrior with special weapon" capitalization is all mismatched and only wracks have the parenthesis thing going on, best to choose one of these formats and stay consistent.

**Venting:**
- [x] I still hate 10 point Reavers, this is like saying "They said killing children was illegal last week, but the laws printed 5 months ago omitted that, so killing children is legal again until they say otherwise again."  It's not a bug but damn it I want to vent because I'm going to have to manually update the points in my catz every time I accidentally update the files until it's fixed.  I'm aware this is how it has to be done. I don't have to like it though.
- [x] _Reaver_ with special weapon is missing points cost for special weapon. Also flags as error when you select anything but Splinter Rifle
- [x] Transports/Units that can be taken in multiple sub factions need the option to select wich obsession they belong to when in a _Real Space Raid_
- [x] Typo in the _Poisoner's Amupule Relic_, there's a space at the wrong place right in the first word
- [x] Archon currently able to take all Warlord Traits regardless of obsession when in a _Mixed Detachment_

**Comment by Dreyven** [comment]
- [x] _Reaver_ with special weapon is missing points cost for special weapon. Also flags as error when you select anything but Splinter Rifle
- [x] Transports/Units that can be taken in multiple sub factions need the option to select wich obsession they belong to when in a _Real Space Raid_
- [x] Typo in the _Poisoner's Amupule Relic_, there's a space at the wrong place right in the first word
- [x] Archon currently able to take all Warlord Traits regardless of obsession when in a _Mixed Detachment_

**Comment by FarseerVeraenthis** [comment]
Lots of things are done.
Regarding the automatic selection of Raiding Forces, this is really hard to implement properly in BS - I've still not quite figured it out - so will be referred to the big brains for further input.
Regarding selecting Cult/Coven/Kabal that is something I'd like to work on too...
Otherwise it should be good to go, apra from the Snowflake Cult of Strife detachments - and of course I noticed that a load of the old wording needs updating....!!
We're nearly there, keep on with the bugs!! :+1: :smile:

**Comment by GusHebblewhite** [comment]
- [x] Phantasm Grenade Launcher currently 'no cost' for Hekatrix Bloodbrides (should be 5pts)
- [x] Kabalite Warrior with Heavy/Special Weapon still has requirement for splinter rifle (Roster Error, should be no such requirement)
- [x] Archon can take Phantasm Grenade Launcher without [legends] warning appearing, even though this is a legends only option.
- [x] No Roster Error for multiple 'Master X' from same obsession in different detachments.
- [x] Obsession benefit text currently incorrect (pre codex I think)

Low Priority (typos and the like):
- [x] Typo on Drazhar 'Master of Blades' aura; "thsi" -> "this" 
- [x] Typo in Grisly Trophies: "suvtract" -> "subtract"
- [x] Empty parentheses after some paragraphs in 'Selection Rules' (where rules reference currently not yet filled in?)

**Comment by Mad-Spy** [comment]
- [x] Archon's Overlord ability is in as a selection entry, but should not be one.

**Comment by FarseerVeraenthis** [comment]
> * [x]  Archon's Overlord ability is in as a selection entry, but should not be one.

It should be, because you can change it in a Realspace Raid 😉

**Comment by Mad-Spy** [comment]
Why would you _not_ make that choice? Stupid GW making it optional.

- [x] Tolerated Ambition shouldn't be available for Warlords, because a Warlord can already have a Trait, and you can't have two using Tolerated Ambition.

**Comment by Sourborn** [comment]
Seems to be no way to select Raiders or Venoms?

**Comment by Duriel201** [comment]
- [x] Shock Prow does not have a tooltip (Raider, Ravager)
- [x] Vehicles still have the Coven/Kabal/Wych Cult Options if you select them in a restricted Cult of Strife detachment

**Comment by Panzer9824** [comment]
- [x] ~~Archon still has Phantasm Grenade Launcher as an option~~ It's a valid Legends option.
- [x] Kabals and Covens still have Obsession-specific troops as options
- [x] Trueborn do not throw an error for including a Heavy weapon in a unit of less than 10
- [x] Trueborn Sybarites do not have a points cost for Phantasm Grenade Launchers
- [x] Throws an error if you use an Archon (maybe others, but that was first noticed) as one of your Infantry units to include a 
transport
- [x] Archon doesn't have access to Kabal-specific warlord traits
- [ ] Taking the Alliance of Agony Core Selection costs 1cp, and giving the WLT to specific HQ also costs 1cp, amounting to a total of 3cp for 2 extra WLT. Should just be 1 total.

**Comment by FarseerVeraenthis** [comment]
> * [ ]  Kabals and Covens still have Obsession-specific troops as options
> * [ ]  Throws an error if you use an Archon (maybe others, but that was first noticed) as one of your Infantry units to include a transport

I do not understand these issues and cannot replicate them, please provide more detail :smile:

**Comment by Panzer9824** [comment]
> 
> 
> > * [ ]   Kabals and Covens still have Obsession-specific troops as options
> > * [ ]   Throws an error if you use an Archon (maybe others, but that was first noticed) as one of your Infantry units to include a transport
> 
> I do not understand these issues and cannot replicate them, please provide more detail 😄

If you have a Haemonculus Coven selected as the detachment's Obsession, you can still select Wyches and Kabalite Warriors for that detachment, and it doesn't throw an error if you do.


I just found it's actually the "special" troops that aren't flagged for allowing transports, not the archon. If you have an Archon, a unit of Trueborn, and two raiders, it will throw an error saying you have a maximum of 1 transport in that detachment.

**Comment by FarseerVeraenthis** [comment]
The first item is a new codex thing, you can have mixed units but only the chosen type will get benefit from the associated obsession.
The second sounds like a bug so I'll get to it later :+1:
Thanks for everything so far!

**Comment by ghost** [comment]
Hello,

- [ ] The warlord traits from the codex supplement for the Cult of Strife are missing : Competitive Edge , Unparalleled Agility and Master Executioner

**Comment by FarseerVeraenthis** [comment]
> Hello,
> 
> * [ ]  The warlord traits from the codex supplement for the Cult of Strife are missing : Competitive Edge , Unparalleled Agility and Master Executioner

Please ensure you have selected the Cult of Strife (Restricted) selection for your Obsession

**Comment by FarseerVeraenthis** [comment]
#9671 is now the leading bug tracker.
