### ISSUE TITLE
Aeldari - Drukhari - Alliance of Agony costs too many CP's

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9678]
**File:** Aeldari - Drukhari.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Reavers should be 20 points/model, not 10 points/model.
Hekatrix of the crudible stratagem not showing as a option.
Alliance of agony is not working properly, it should give a haemy and succubus traits.

**Comment by Valorcalls** [comment]
Part 1 is false, latest release of costs is the DE codex, which is 10pts, not 20.
2 only shows up as an option if your army contains a cult of strife detachment using the rules set forth in War Zone Charadon, please confirm you are using that detachment.
3 appears to work fine in function, however it is charging CPs both to unlock the strat itself, and for both upgrades on the upgraded characters. This is making it cost 3cps instead of 1 cp.

**Comment by KalChoedan** [comment]
> Part 1 is false, latest release of costs is the DE codex, which is 10pts, not 20.

FWIW this is a typo in the English release of the Codex. Other language versions have the value at 20.

**Comment by npavlinsky** [comment]
the 10 point cost on reavers in the English Codex is widely excepted as a misprint. As multiple other language releases of the codex list them as 20 points.

**Comment by alphalas** [comment]
Until it is FAQ'd it stays because the translations tend to be incorrect more often then not.
