### ISSUE TITLE
Issue with the Knight Warlord traits from Psychic Awakening: Engine War 

### ISSUE THREAD

**Issue by trepidoat** [BSData/wh40k-9e#9704]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** All

**Dropbox:** No

**Description:** The Knight Warlord traits from Psychic Awakening: Engine War are only accessible via a detachment warlord. They should also be available via the Exalted Court stratagem selection also.

**Comment by Mad-Spy** [comment]
This is incorrect. The FAQ/errata to Engine War states that models which can take warlord traits via a Stratagem are not considered to be a Warlord for determining which Warlord Traits they have access to.

![image](https://user-images.githubusercontent.com/29306451/114004983-0cd82280-9857-11eb-9e25-5699c03f8661.png)

**Comment by trepidoat** [comment]
Thank you for the clarification and for keeping me right @Mad-Spy I assume by extension this refers to the Exalted Court stratagem also (rather than the Mechanicus Locum Strat noted above)

**Comment by DrTobogganMD** [comment]
@trepidoat Correct, that FAQ is used as precedent for all similar items with the same wording, including the Exalted Court.

**Comment by surferdibz** [comment]
Am I able to question this thinking please @DrTobogganMD, because that precedent seems incorrect. 

The Questor Allegiance warlord traits page in Engine War states the traits can be used instead of those presented in other publications. So they can be used to override the Imperial Knights warlord traits in Codex: Imperial Knights and should be available to the Exalted Court Imperial Knights stratagem. This behaviour is in exactly the same way that Household specific warlord traits are provided in Codex: Imperial Knights and they can be taken in place of Imperial Knights Warlord traits from Codex: Imperial Knights. 

The current version of the Imperial Knights force allows the Exalted Court strategem to take Imperial Knights warlord traits and it allows you to take Household warlord traits. So either it should also allow Engine War Questor Allegiance traits (as I believe it should) or it shouldn't allow the Household traits and should only allow the generally available warlord traits (which I don't believe to be a distinction anyone is making, as a set of traits substituting another set of traits is pretty commonplace).

@Mad-Spy How would you be able to give anyone other than your warlord a warlord trait if that was the case? Since you can only give your warlord a warlord trait, according to the warlord traits section. These stratagems supersede that by stating the Character is regarded as warlord for the purpose of being given a trait, and for the effects granted by the trait only. The cited FAQ requires challenging as incorrect since it doesn't make sense and doesn't answer the question asked. (Obviously nothing to do with you, but it is a dangerous thing to base a general precedent on).

this could also relate to #9675

**Comment by DrTobogganMD** [comment]
Engine War WTs (Admech): 
![image](https://user-images.githubusercontent.com/16939161/114074616-2e8ed500-986a-11eb-88ce-1bd7d87018a8.png)
Engine War WTs (IK):
![image](https://user-images.githubusercontent.com/16939161/114074711-4a927680-986a-11eb-9a8d-eb0dc7ce72d1.png)

Extra WT Strat (Admech):
![image](https://user-images.githubusercontent.com/16939161/114074793-64cc5480-986a-11eb-8675-107589fb4fa7.png)
Extra WT Strat (IK):
![image](https://user-images.githubusercontent.com/16939161/114074822-6d248f80-986a-11eb-8a66-27d263dc2da4.png)

They are worded the same in each case. The FAQ carries over. It is not an ambiguous issue.

**Comment by surferdibz** [comment]
I understand they are worded the same in each case, but the scenario is identical to how you can replace an Imperial Knights warlord trait with a Household warlord trait. The cat file allows for this. So if you are certain the Exalted Court stratagem should only allow the use of Imperial Knight warlord traits from the Codex, it shouldn't allow the use of a Household trait instead on the same grounds. 

Rules as written on that FAQ that has been cited, you wouldn't be able to give the character any warlord trait, as they aren't the warlord. The FAQ says they are only considered to be the warlord for the purpose of the trait itself, not for which traits they can take. Only warlords can take warlord traits. The FAQ answer contradicts the whole stratagem and rule as it is widely understand (and again - already implemented with the Imperial Knights cat with regard to Household traits).

Sorry to be a dog with a bone on this one. I don't mean anything by it, I simply think it is dangerous to hang a precedent on what appears to be an incorrect answer to a specific FAQ on one faction and situation to all other factions where there are no rules as written to support the behaviour implemented.  Precedent is effectively equivalent to Intent in this situation since the FAQ ("Rule") doesn't mention Imperial Knights but is being applied to Imperial Knights rules. This doesn't sound like Rules as Written.

I can see why you the current approach has been taken, and I can see why I think it should align with how the household specific traits have been treated, either way, the current implementation isn't consistent with either decision, its some of one, some of the other.

**Comment by WindstormSCR** [comment]
Well, right now the only argument you have successfully made is that per the wording of that FAQ, every single instance of the extra warlord trait stratagems should cease to function. Shall we point everyone here when we make that change?

**Comment by surferdibz** [comment]
> Well, right now the only argument you have successfully made is that per the wording of that FAQ, every single instance of the extra warlord trait stratagems should cease to function. Shall we point everyone here when we make that change?

If you want to apply the rule consistently, I guess, yes? (sorry, I'm not sure if I am to take your reply as sarcasm, just snark, or a genuine question). I'm guessing on all counts you disagree with my confusion about the inconsistency of how this limitation is or isn't applied? I'd be interested on your take of how the FAQ cited should be applied? 

What I'm suggesting is, based on the stratagem existing, and allowing someone to give a second character a second warlord trait when they aren't a warlord. And given that all warlord trait sections of rule books are written as a kind of superset or override/overload where you can choose to replace the list of warlord traits a warlord can pick from with 'this other list of warlord traits' if you wish, my angle is that the engine war traits should be available to an exalted court stratagem character, or the Holy Order traits should be available to the Mechanicus Locus stratagem. I guess what I'm really suggesting is that the FAQ is actually an Error, in the Errata. 

Really, honestly, I'm not having a go or trying it on or anything. I was genuinely trying to help, and I'm possibly mis-interpreting the replies to my comments as stand-off and dismissive much the same as I fear my comments are being taken as bolshy or aggressive or something (because its a wall of text and very picky/finickity).

Apologies if I'm out of line, and of course, I'm really not expecting anything to change in the 40kData as a result of this as it is clear you have an angle and believe it to be correct, which is really all any of us can do with this particular ruleset!

Thanks for all the time taken to reply.
