### ISSUE TITLE
Black Templar (and probably other Space Marines) - 'Angel of Death' - 'And They Will Know No Fear' and 'Combat Doctrines' not showing in output

### ISSUE THREAD

**Issue by rosenthal-s** [BSData/wh40k-9e#9873]
**File/Catalogue:** 

**BattleScribe version:** 2.03.21.

**Platform:** Windows

**Dropbox:** No

**Description:** I'm building a new Black Templars list, and the 4 rules shown under 'Angels of Death' are the following:
- And They Shall Know No Fear
- Bolter Discipline
- Shock Assault
- Combat Doctrines

However, only Bolter Discipline and Shock Assault are shown on the roster output.

![image](https://user-images.githubusercontent.com/29211712/119128897-265fb300-ba2e-11eb-97a1-0fc3597b6409.png)

**Comment by WindstormSCR** [comment]
That's what your codex is for

**Comment by rosenthal-s** [comment]
> That's what your codex is for

Well by that logic isn't your codex for all the rules then? Why even bother displaying anything in the roster except a list of units at that point? Because the info here is supposed to help you play the game without having to flick through books, and I'm just wondering why these specific bits of info are missing.

**Comment by alphalas** [comment]
@UnidentifiedBody The text was omitted because the way battlescribe will produce large blocks of text like that means it'll take up a page and a half of just straight text making the rosters large, unwieldy, and nearly unusable once printed out. Battlescribe is not a codex replacement by any stretch of the imagination, so saying you use it so you don't have to flip through the codex is not a valid argument around here.￼
