### ISSUE TITLE
Imperium - Imperial Knights: No option to mark detachment as Knight of the Cog

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-9e#9908]
**File:** Imperium - Imperial Knights.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When you include a Questor Mechanicus Knight in your Ad Mech Army via a Super Heavy Aux detachment, there is no option to grant your Knight with the “Knight of the Cog” keyword.

**Comment by Mad-Spy** [comment]
Does this actually have any list building effect?

**Comment by Pacemagnet** [comment]
It’s required for canticles to work for your ad mech army if you’re fielding a knight in a super heavy aux:

-DOCTRINA IMPERATIVES / CANTICLES OF THE OMNISSIAH - “If every unit from your army has the ADEPTUS MECHANICUS keyword (excluding AGENT OF THE IMPERIUM, UNALIGNED, and KNIGHT OF THE COG units) this unit […]”

-KNIGHT OF THE COG - “For each Detachment in your army with this ability, you can select a QUESTOR MECHANICUS Super-heavy Auxiliary Detachment in your army. Models in that Detachment gain the KNIGHT OF THE COG keyword.“

It’s a detachment ability that allows canticles. It was even featured on Goonhammer (Item #10 https://www.goonhammer.com/ruleshammer-adeptus-mechanicus/)

**Comment by Mad-Spy** [comment]
Right, so no actual effect that unlocks anything you need to add at list building time. You just need to say to your opponent "this is a knight of the cog detachment" when you play.

We don't usually add options that do nothing from a list building point of view, but it's up to @DrTobogganMD as to whether he wants to add it.

**Comment by DrTobogganMD** [comment]
So, the lines that are relevant from goonhammer (thanks for the link, that's a great unpacking of a very confusing interaction):

In summary, there are two ways to include Imperial Knights in an Admech army without breaking Doctrinas and Canticles:

Knight of the Cog: For each Admech detachment in your army, you may include a single Imperial Knight Super-heavy Auxiliary Detachment. The presence of Imperial Knights in these Super-heavy Auxility detachments do not affect Doctrinas or Canticles.
Knight of the Iron Cog: If you have a Metalica Admech detachment, you may include any number of Imperial Knights in Super-heavy Detachments. If you do this, then you must you use the Knight of the Iron Cog strategem on each of those Imperial Knights in order for Doctrinas and Canticles to remain functional.

Because you can only have a single Knight of the Cog per admech detachment (and taking more knights without KotIC invalidates canticles), I would agree that it would be beneficial to state on the list which is KotC. This allows TOs to correctly verify you are allowed to have canticles. I'll start looking at how best to implement it today.

**Comment by Pacemagnet** [comment]
Thank you! I’m glad I could be of assistance! I know it’s quite a small change, but my concern was always from a tournament perspective.

**Comment by Pacemagnet** [comment]
@DrTobogganMD Hey I saw the ticket was closed, I’m assuming this is now active in BattleScribe? Could you let me know how to place Knight of the Cog on my knight? Thank you!!!

**Comment by DrTobogganMD** [comment]
It is not live yet. Our next release will be on Saturday

**Comment by Pacemagnet** [comment]
Thank you!!!! You rock!

**Comment by Pacemagnet** [comment]
@DrTobogganMD Hey sorry to bother, but when I checked BattleScribe yesterday, I was unable to assign Knight of the Cog to my Knight Crusader. Can you detail how I’m supposed to do this? Sorry again, and thank you!

**Comment by DrTobogganMD** [comment]
Hmm, looks like my fix didn't fix.  Working on it.
