### ISSUE TITLE
Imperial - Adepta Sororitas - 9E Codex Update

### ISSUE THREAD

**Issue by CrusherJoe** [BSData/wh40k-9e#9951]
[this list is a WIP]

Checklist for changes/edit/updates.

### Outstanding Bugs
- [x] You can take more PRIESTS than ADEPTAS SORORITAS CHARACTERs in a detachment. (See Page 57)
- [x] Order Convictions should default to "Adeptus Ministorum"
- [x] Ranged Weapons SSEG doesn't display when "Bolt Pistol & Ranged Weapon" option is chosen under Wargear Options for Sister/Celestian/Dominion/Retributor Superior 
- [x] Intentional: ~~Order-specific Relics of the Ecclesiarchy only become available if Warlord is selected (Quicksilver Veil, Beneficence, etc.)~~

### New Units
- [x] Morvenn Vahl
- [x] Paragon Warsuits
- [x] Dogmata
- [x] Celestian Sacresants
- [x] Aestred Thurga and Agathae Dolan
- [x] Castigator

### New Rules
- [x] Minoris Convictions
- [x] Blessings of the Faithful
- [x] Hymns of Battle
- [x] "Relic: The Sigil Ecclesiasticus" needs to increase available Hymns count

### Points/Wargear:
- [x] Condemnor Boltgun from 5 to 10
- [x] Nullrod from 0 to 10 
- [x] Rod of Office from 0 to 5
- [x] Artificier Crafted Stormbolter 5
- [x] Ministorum Hand flamer 5
- [x] Ministorum Combi-flamer 10
- [x] Ministorum Flamer 5
- [x] Ministorum Heavy Flamer 10
- [x] Simulacrum from 0 to 5
- [x] Spear of the Faithful 5 (Sacresants)
- [x] Castigator battle Cannon 5
- [x] Twin Multi-Melta from 20 to 30
- [x] Immolation Flamer from 0 to 10

### HQ:
- [x] Celestine from 170 to 200 (Geminae Baked in)
- [x] Ephareal Stren and the elf boy from 125 to 120
- [x] Junith Eruita from 115 to 130
- [x] Missionary from 45 to 40
- [x] Morven Vahl 265
- [x] Triumph of St Katherine from 195 to 220

### Elite:
- [x] Astred Thurga and Agathae Dolan 90
- [x] Arcos from 15 to 13
- [x] Celestians from 12 to 13
- [x] Celestian Sacresants 14
- [x] Crusaders from 16 to 11
- [x] Dialogus from 40 to 50
- [x] Dogmata 65
- [x] Hospitaler from 40 to 50
- [x] Imagifier from 45 to 50
- [x] Paragon Warsuits 80
- [x] Preacher from 35 to 25
- [x] Repentia from 16 to 14

### Fast Attack:
- [x] Seraphim from 15 to 14
- [x] Zephyrim from 18 to 17

### Heavy Support:
- [x] Castigator 160
- [x] Exorcist from 165 to 150
- [x] Peninent Engine from 50 to 55
- [x] Retributor from 14 to 12

### Deticated Transport:
- [x] Immolator from 125 to 120

### Unit/Rule Updates:
- [x] Battle Sisters
- [x] Celestine
- [x] Palatine
- [x] Canoness
- [x] Imagifier
- [x] Dialogus
- [x] Hospitaller
- [x] Preacher
- [x] Missionary
- [x] Repentia Superior
- [x] Triumph
- [x] Junith Eruita
- [x] Celestian Squad
- [x] Sisters Repentia
- [x] Crusaders
- [x] Arco-Flagellants
- [x] DCA
- [x] Dominion Squad
- [x] Seraphim
- [x] Zephyrim
- [x] Retributor Squad
- [x] Morts
- [x] Pengines
- [x] Exorcist
- [x] Rhino
- [x] Immolator
- [x] Battle Sanctum

Post-Merge
- [x] Remove Stern & friends from all non-sisters imperium cats.

**Comment by Serdain** [comment]
Beta Testing
- [x] Penitent Engine Stateline Missing
- [x] Tale of the Warrior (Imagifier) says Add 1 Stregth
- [x] Psalm of Righteous Smiting reads 'Et the end of the fight phase'. Should read 'At'
- [x] Saint in the making ends in a '/' instead of '.'
- [x] Non-militant order (hospitallier) reads 'Detacmet' instead of 'Detachment' 
- [x] Arco Flagellant Weapons read "Make D3 hit rolls for each attack with this weapon instead of 1." Has been changed to 2, from D3.
- [x] ~~Arco Flag with Endurant Implants do not have altered statlines (maybe not a bug ??)~~
- [x] Vahl's Explosion rules describe her as a Transport (should be model)
- [x] Saint in the making does not pluralise "trait" when specifying multiple can be selected. 
- [x] Executioner of Heretics reads "Each time a combat attrition test is takes for that unit", rather than "taken"
- [x] The Sigil Ecclesiaticus refers to Hymns as Hymms
